name: pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]
      
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    # More info on options: https://github.com/marketplace/actions/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/ael-test.yaml
        channels: conda-forge, pytorch
        activate-environment: ael-test
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true

    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list

    - name: Run tests
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        pytest -v --cov=ael --cov-report=xml --color=yes tests/

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: 9fca75c0-b2d0-408b-bd85-f33f0d1f523d
        file: ./coverage.xml
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        fail_ci_if_error: true
        verbose: false
